# Generated by Django 5.2.7 on 2025-10-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
